#pipeline:
#  Stage 1:
#    image: breezestars/mars-test:0.1
#    commands:
#       - ip addr
#
#  backend#    image: golang
#    secrets: [ test ]
#    commands:
#      - echo "backend testing"
#      - echo $TEST
# 
#  frontend:
#    image: golang
#    commands:
#      - echo "frontend testing"
#
pipeline {
    agent none
    stages {
        stage('say hi') {
            steps {
                echo "I don't need no node"
            }
        }
        stage('build') {
             agent {
                 label 'master'
             }
             steps {   
                checkout scm
                sh 'echo from master'
            }
        }
        stage('deploy') {
            agent {
                label 'deploy-host'
            }
            steps {
                sh './deploy-code-here'
            }
        }
    }
}

